<?php

namespace Database\Seeders;

use App\Models\Mapel;
use Illuminate\Database\Seeder;

class MapelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Mapel::truncate();


        $data = [
            [
                "id" => 1,
                "id_namamapel" => 1,
                "mapel" => "Pendidikan Agama Islam & Budi Pekerti",
                "guru_mapel" => "1",
                "kelas" => "1",
                "kkm" => null,
            ],
            [
                "id" => 2,
                "id_namamapel" => 2,
                "mapel" => "Pendidikan Pancasila & Kewarganegaraan",
                "guru_mapel" => "0",
                "kelas" => "1",
                "kkm" => null,
            ],
            [
                "id" => 3,
                "id_namamapel" => 3,
                "mapel" => "Bahasa Indonesia",
                "guru_mapel" => "0",
                "kelas" => "1",
                "kkm" => null,
            ],
            [
                "id" => 4,
                "id_namamapel" => 4,
                "mapel" => "Matematika",
                "guru_mapel" => "0",
                "kelas" => "1",
                "kkm" => null,
            ],
            [
                "id" => 5,
                "id_namamapel" => 5,
                "mapel" => "Ilmu Pengetahuan Alam",
                "guru_mapel" => "0",
                "kelas" => "1",
                "kkm" => null,
            ],
            [
                "id" => 6,
                "id_namamapel" => 6,
                "mapel" => "Ilmu Pengetahuan Sosial",
                "guru_mapel" => "0",
                "kelas" => "1",
                "kkm" => null,
            ],
            [
                "id" => 7,
                "id_namamapel" => 7,
                "mapel" => "Seni Budaya & Prakarya",
                "guru_mapel" => "0",
                "kelas" => "1",
                "kkm" => null,
            ],
            [
                "id" => 8,
                "id_namamapel" => 8,
                "mapel" => "Pendidikan Jasmani Olahraga & Kesehatan",
                "guru_mapel" => "0",
                "kelas" => "1",
                "kkm" => null,
            ],
            [
                "id" => 9,
                "id_namamapel" => 9,
                "mapel" => "Bahasa Jawa",
                "guru_mapel" => "0",
                "kelas" => "1",
                "kkm" => null,
            ],
            [
                "id" => 10,
                "id_namamapel" => 10,
                "mapel" => "Bahasa Inggris",
                "guru_mapel" => "1",
                "kelas" => "1",
                "kkm" => null,
            ],
            [
                "id" => 11,
                "id_namamapel" => 1,
                "mapel" => "Pendidikan Agama Islam & Budi Pekerti",
                "guru_mapel" => "1",
                "kelas" => "2",
                "kkm" => null,
            ],
            [
                "id" => 12,
                "id_namamapel" => 2,
                "mapel" => "Pendidikan Pancasila & Kewarganegaraan",
                "guru_mapel" => "0",
                "kelas" => "2",
                "kkm" => null,
            ],
            [
                "id" => 13,
                "id_namamapel" => 3,
                "mapel" => "Bahasa Indonesia",
                "guru_mapel" => "0",
                "kelas" => "2",
                "kkm" => null,
            ],
            [
                "id" => 14,
                "id_namamapel" => 4,
                "mapel" => "Matematika",
                "guru_mapel" => "0",
                "kelas" => "2",
                "kkm" => null,
            ],
            [
                "id" => 15,
                "id_namamapel" => 5,
                "mapel" => "Ilmu Pengetahuan Alam",
                "guru_mapel" => "0",
                "kelas" => "2",
                "kkm" => null,
            ],
            [
                "id" => 16,
                "id_namamapel" => 6,
                "mapel" => "Ilmu Pengetahuan Sosial",
                "guru_mapel" => "0",
                "kelas" => "2",
                "kkm" => null,
            ],
            [
                "id" => 17,
                "id_namamapel" => 7,
                "mapel" => "Seni Budaya & Prakarya",
                "guru_mapel" => "0",
                "kelas" => "2",
                "kkm" => null,
            ],
            [
                "id" => 18,
                "id_namamapel" => 8,
                "mapel" => "Pendidikan Jasmani Olahraga & Kesehatan",
                "guru_mapel" => "0",
                "kelas" => "2",
                "kkm" => null,
            ],
            [
                "id" => 19,
                "id_namamapel" => 9,
                "mapel" => "Bahasa Jawa",
                "guru_mapel" => "0",
                "kelas" => "2",
                "kkm" => null,
            ],
            [
                "id" => 20,
                "id_namamapel" => 10,
                "mapel" => "Bahasa Inggris",
                "guru_mapel" => "1",
                "kelas" => "2",
                "kkm" => null,
            ],
            [
                "id" => 21,
                "id_namamapel" => 1,
                "mapel" => "Pendidikan Agama Islam & Budi Pekerti",
                "guru_mapel" => "1",
                "kelas" => "3",
                "kkm" => null,
            ],
            [
                "id" => 22,
                "id_namamapel" => 2,
                "mapel" => "Pendidikan Pancasila & Kewarganegaraan",
                "guru_mapel" => "0",
                "kelas" => "3",
                "kkm" => null,
            ],
            [
                "id" => 23,
                "id_namamapel" => 3,
                "mapel" => "Bahasa Indonesia",
                "guru_mapel" => "0",
                "kelas" => "3",
                "kkm" => null,
            ],
            [
                "id" => 24,
                "id_namamapel" => 4,
                "mapel" => "Matematika",
                "guru_mapel" => "0",
                "kelas" => "3",
                "kkm" => null,
            ],
            [
                "id" => 25,
                "id_namamapel" => 5,
                "mapel" => "Ilmu Pengetahuan Alam",
                "guru_mapel" => "0",
                "kelas" => "3",
                "kkm" => null,
            ],
            [
                "id" => 26,
                "id_namamapel" => 6,
                "mapel" => "Ilmu Pengetahuan Sosial",
                "guru_mapel" => "0",
                "kelas" => "3",
                "kkm" => null,
            ],
            [
                "id" => 27,
                "id_namamapel" => 7,
                "mapel" => "Seni Budaya & Prakarya",
                "guru_mapel" => "0",
                "kelas" => "3",
                "kkm" => null,
            ],
            [
                "id" => 28,
                "id_namamapel" => 8,
                "mapel" => "Pendidikan Jasmani Olahraga & Kesehatan",
                "guru_mapel" => "0",
                "kelas" => "3",
                "kkm" => null,
            ],
            [
                "id" => 29,
                "id_namamapel" => 9,
                "mapel" => "Bahasa Jawa",
                "guru_mapel" => "0",
                "kelas" => "3",
                "kkm" => null,
            ],
            [
                "id" => 30,
                "id_namamapel" => 10,
                "mapel" => "Bahasa Inggris",
                "guru_mapel" => "1",
                "kelas" => "3",
                "kkm" => null,
            ],
            [
                "id" => 31,
                "id_namamapel" => 1,
                "mapel" => "Pendidikan Agama Islam & Budi Pekerti",
                "guru_mapel" => "1",
                "kelas" => "4",
                "kkm" => null,
            ],
            [
                "id" => 32,
                "id_namamapel" => 2,
                "mapel" => "Pendidikan Pancasila & Kewarganegaraan",
                "guru_mapel" => "0",
                "kelas" => "4",
                "kkm" => null,
            ],
            [
                "id" => 33,
                "id_namamapel" => 3,
                "mapel" => "Bahasa Indonesia",
                "guru_mapel" => "0",
                "kelas" => "4",
                "kkm" => null,
            ],
            [
                "id" => 34,
                "id_namamapel" => 4,
                "mapel" => "Matematika",
                "guru_mapel" => "0",
                "kelas" => "4",
                "kkm" => null,
            ],
            [
                "id" => 35,
                "id_namamapel" => 5,
                "mapel" => "Ilmu Pengetahuan Alam",
                "guru_mapel" => "0",
                "kelas" => "4",
                "kkm" => null,
            ],
            [
                "id" => 36,
                "id_namamapel" => 6,
                "mapel" => "Ilmu Pengetahuan Sosial",
                "guru_mapel" => "0",
                "kelas" => "4",
                "kkm" => null,
            ],
            [
                "id" => 37,
                "id_namamapel" => 7,
                "mapel" => "Seni Budaya & Prakarya",
                "guru_mapel" => "0",
                "kelas" => "4",
                "kkm" => null,
            ],
            [
                "id" => 38,
                "id_namamapel" => 8,
                "mapel" => "Pendidikan Jasmani Olahraga & Kesehatan",
                "guru_mapel" => "0",
                "kelas" => "4",
                "kkm" => null,
            ],
            [
                "id" => 39,
                "id_namamapel" => 9,
                "mapel" => "Bahasa Jawa",
                "guru_mapel" => "0",
                "kelas" => "4",
                "kkm" => null,
            ],
            [
                "id" => 40,
                "id_namamapel" => 10,
                "mapel" => "Bahasa Inggris",
                "guru_mapel" => "1",
                "kelas" => "4",
                "kkm" => null,
            ],
            [
                "id" => 41,
                "id_namamapel" => 1,
                "mapel" => "Pendidikan Agama Islam & Budi Pekerti",
                "guru_mapel" => "1",
                "kelas" => "5",
                "kkm" => null,
            ],
            [
                "id" => 42,
                "id_namamapel" => 2,
                "mapel" => "Pendidikan Pancasila & Kewarganegaraan",
                "guru_mapel" => "0",
                "kelas" => "5",
                "kkm" => null,
            ],
            [
                "id" => 43,
                "id_namamapel" => 3,
                "mapel" => "Bahasa Indonesia",
                "guru_mapel" => "0",
                "kelas" => "5",
                "kkm" => null,
            ],
            [
                "id" => 44,
                "id_namamapel" => 4,
                "mapel" => "Matematika",
                "guru_mapel" => "0",
                "kelas" => "5",
                "kkm" => null,
            ],
            [
                "id" => 45,
                "id_namamapel" => 5,
                "mapel" => "Ilmu Pengetahuan Alam",
                "guru_mapel" => "0",
                "kelas" => "5",
                "kkm" => null,
            ],
            [
                "id" => 46,
                "id_namamapel" => 6,
                "mapel" => "Ilmu Pengetahuan Sosial",
                "guru_mapel" => "0",
                "kelas" => "5",
                "kkm" => null,
            ],
            [
                "id" => 47,
                "id_namamapel" => 7,
                "mapel" => "Seni Budaya & Prakarya",
                "guru_mapel" => "0",
                "kelas" => "5",
                "kkm" => null,
            ],
            [
                "id" => 48,
                "id_namamapel" => 8,
                "mapel" => "Pendidikan Jasmani Olahraga & Kesehatan",
                "guru_mapel" => "0",
                "kelas" => "5",
                "kkm" => null,
            ],
            [
                "id" => 49,
                "id_namamapel" => 9,
                "mapel" => "Bahasa Jawa",
                "guru_mapel" => "0",
                "kelas" => "5",
                "kkm" => null,
            ],
            [
                "id" => 50,
                "id_namamapel" => 10,
                "mapel" => "Bahasa Inggris",
                "guru_mapel" => "1",
                "kelas" => "5",
                "kkm" => null,
            ],
            [
                "id" => 51,
                "id_namamapel" => 1,
                "mapel" => "Pendidikan Agama Islam & Budi Pekerti",
                "guru_mapel" => "1",
                "kelas" => "6",
                "kkm" => null,
            ],
            [
                "id" => 52,
                "id_namamapel" => 2,
                "mapel" => "Pendidikan Pancasila & Kewarganegaraan",
                "guru_mapel" => "0",
                "kelas" => "6",
                "kkm" => null,
            ],
            [
                "id" => 53,
                "id_namamapel" => 3,
                "mapel" => "Bahasa Indonesia",
                "guru_mapel" => "0",
                "kelas" => "6",
                "kkm" => null,
            ],
            [
                "id" => 54,
                "id_namamapel" => 4,
                "mapel" => "Matematika",
                "guru_mapel" => "0",
                "kelas" => "6",
                "kkm" => null,
            ],
            [
                "id" => 55,
                "id_namamapel" => 5,
                "mapel" => "Ilmu Pengetahuan Alam",
                "guru_mapel" => "0",
                "kelas" => "6",
                "kkm" => null,
            ],
            [
                "id" => 56,
                "id_namamapel" => 6,
                "mapel" => "Ilmu Pengetahuan Sosial",
                "guru_mapel" => "0",
                "kelas" => "6",
                "kkm" => null,
            ],
            [
                "id" => 57,
                "id_namamapel" => 7,
                "mapel" => "Seni Budaya & Prakarya",
                "guru_mapel" => "0",
                "kelas" => "6",
                "kkm" => null,
            ],
            [
                "id" => 58,
                "id_namamapel" => 8,
                "mapel" => "Pendidikan Jasmani Olahraga & Kesehatan",
                "guru_mapel" => "0",
                "kelas" => "6",
                "kkm" => null,
            ],
            [
                "id" => 59,
                "id_namamapel" => 9,
                "mapel" => "Bahasa Jawa",
                "guru_mapel" => "0",
                "kelas" => "6",
                "kkm" => null,
            ],
            [
                "id" => 60,
                "id_namamapel" => 10,
                "mapel" => "Bahasa Inggris",
                "guru_mapel" => "1",
                "kelas" => "6",
                "kkm" => null,
            ],
        ];


        foreach ($data as $item) {
            Mapel::create([
                "nama"=> $item['mapel'],
                "kelas"=> $item['kelas'],
                "kelas"=> $item['kelas'],
                "kkm"=> $item['kkm'],
                "guru_mapel"=> $item['guru_mapel'] == "1" ? true:false,
            ]);

        }
    }
}
